name: Update Xcode Version

on:
  # Allow to be run manually
  workflow_dispatch:
  # Run at 8am UTC daily
  schedule:
    - cron: "0 8 * * *"

jobs:
  update-xcode-version:
    name: Update Xcode Version
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.UPDATE_XCODE_VERSIONS_GITHUB_TOKEN }}

      - uses: josephduffy/update-xcode-version-action@0.4.0
        with:
          xcode-version-badge-versions: "11.7, last-major, latest"
          xcode-version-badge-markdown-file: ./README.md
          github-token: ${{ secrets.GITHUB_TOKEN }}
